### ISSUE TITLE
Weird audio noises (Please help me asap)

### ISSUE THREAD

**Issue by ilitvinenko90** [slavavdovichenko/MediaLibDemos3x#45]
I have app that should stream video from iPad app to iPhone app. It is 2 different applications. 
We using Wowza streaming engine for it, at our backend.

I using custom mode, because I need to send live streamed video from iPad main screen. 
But when I begin streaming video, there is annoying noise from iPad speaker. It happen only with production builds, but with development everything is ok. So I need to always generate .ipa file, for each test. 

Thank you on advance for you help.

**Comment by slavavdovichenko** [comment]
Maybe you use 
[MPMediaData routeAudioToSpeaker];
somewhere?

**Comment by ilitvinenko90** [comment]
I found this method in your framework, but I don't call it anywhere. Checked twice. 
I can send you class that work with stream.

**Comment by slavavdovichenko** [comment]
can you give me your project (without "lib" folder) for investigation this problem?
my email: slavav@themidnightcoders.com

**Comment by ilitvinenko90** [comment]
Should I send whole project?

**Comment by slavavdovichenko** [comment]
Yes - if you can

**Comment by ilitvinenko90** [comment]
Can I just send file that integrated with lib because, my client don't wan't to show source code?

**Comment by slavavdovichenko** [comment]
OK, - maybe I be able to reproduce the problem

**Comment by ilitvinenko90** [comment]
Can we communicate via Skype in russian? It will be easy for me to describe everything for you?

My Skype id: onegin166

**Comment by ilitvinenko90** [comment]
Now preparing email with file and description for you, will send it shortly

**Comment by ilitvinenko90** [comment]
Just sent it

**Comment by jbeoris** [comment]
Was this issue ever fixed or resolved? I am having the exact same issue.

**Comment by slavavdovichenko** [comment]
You should not use 
[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryRecord error:&error];
in your code.
If you need to set some AVAudioSession categories you have to use the MPMediaData class method:
+(void)setAVAudioSessionCategoryPlayAndRecord:(AVAudioSessionCategoryOptions)options;

**Comment by slavavdovichenko** [comment]
This issue is fixed - you can try again

**Comment by ilitvinenko90** [comment]
> This issue is fixed - you can try again
Looks like it's still exist. I already tried to use MPMediaData. But not help.

**Comment by BigDipperStar** [comment]
Downloaded final version and retry it too.
But I found same problems on my project.
i can hear noise sometimes and it is crashed too.
